// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: pkg/proto/editor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EditorService_JoinSession_FullMethodName   = "/editor.EditorService/JoinSession"
	EditorService_BroadcastEdit_FullMethodName = "/editor.EditorService/BroadcastEdit"
)

// EditorServiceClient is the client API for EditorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EditorServiceClient interface {
	JoinSession(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	BroadcastEdit(ctx context.Context, in *EditRequest, opts ...grpc.CallOption) (*EditResponse, error)
}

type editorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEditorServiceClient(cc grpc.ClientConnInterface) EditorServiceClient {
	return &editorServiceClient{cc}
}

func (c *editorServiceClient) JoinSession(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinResponse)
	err := c.cc.Invoke(ctx, EditorService_JoinSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editorServiceClient) BroadcastEdit(ctx context.Context, in *EditRequest, opts ...grpc.CallOption) (*EditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditResponse)
	err := c.cc.Invoke(ctx, EditorService_BroadcastEdit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EditorServiceServer is the server API for EditorService service.
// All implementations must embed UnimplementedEditorServiceServer
// for forward compatibility.
type EditorServiceServer interface {
	JoinSession(context.Context, *JoinRequest) (*JoinResponse, error)
	BroadcastEdit(context.Context, *EditRequest) (*EditResponse, error)
	mustEmbedUnimplementedEditorServiceServer()
}

// UnimplementedEditorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEditorServiceServer struct{}

func (UnimplementedEditorServiceServer) JoinSession(context.Context, *JoinRequest) (*JoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinSession not implemented")
}
func (UnimplementedEditorServiceServer) BroadcastEdit(context.Context, *EditRequest) (*EditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastEdit not implemented")
}
func (UnimplementedEditorServiceServer) mustEmbedUnimplementedEditorServiceServer() {}
func (UnimplementedEditorServiceServer) testEmbeddedByValue()                       {}

// UnsafeEditorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EditorServiceServer will
// result in compilation errors.
type UnsafeEditorServiceServer interface {
	mustEmbedUnimplementedEditorServiceServer()
}

func RegisterEditorServiceServer(s grpc.ServiceRegistrar, srv EditorServiceServer) {
	// If the following call pancis, it indicates UnimplementedEditorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EditorService_ServiceDesc, srv)
}

func _EditorService_JoinSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditorServiceServer).JoinSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EditorService_JoinSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditorServiceServer).JoinSession(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EditorService_BroadcastEdit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditorServiceServer).BroadcastEdit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EditorService_BroadcastEdit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditorServiceServer).BroadcastEdit(ctx, req.(*EditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EditorService_ServiceDesc is the grpc.ServiceDesc for EditorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EditorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "editor.EditorService",
	HandlerType: (*EditorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinSession",
			Handler:    _EditorService_JoinSession_Handler,
		},
		{
			MethodName: "BroadcastEdit",
			Handler:    _EditorService_BroadcastEdit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/editor.proto",
}
